# Generated by Django 4.2 on 2023-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_sent_by_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_required',
            field=models.BooleanField(default=False, help_text='whether the participant is essential to the conversation', verbose_name='is required'),
        ),
    ]
