# Generated by Django 4.0.2 on 2022-02-02 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='participant')),
                ('is_present', models.BooleanField(verbose_name='is present')),
                ('type', models.CharField(choices=[('H', 'human'), ('B', 'bot')], default=None, max_length=1, verbose_name='type')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='chat.conversation', verbose_name='participants')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('S', 'System'), ('T', 'Text'), ('V', 'Voice'), ('M', 'Media'), ('A', 'Attachment')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('text', models.CharField(blank=True, max_length=4000, verbose_name='text')),
                ('additional_metadata', models.JSONField(blank=True, default=dict, verbose_name='additional metadata')),
                ('original_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='original file name')),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='original file name')),
                ('local_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='local message id')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='chat.conversation', verbose_name='message')),
                ('quoted_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message', verbose_name='quoted message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.participant', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
