# Generated by Django 4.0.2 on 2022-02-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_conversation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sender', 'local_id'), name='local_id_unique'),
        ),
    ]
