# Generated by Django 4.0.2 on 2022-02-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_local_id_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_present',
        ),
    ]
