# Generated by Django 4.0.2 on 2022-03-29 14:40

import chat.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_participant_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=chat.models._attachment_name, verbose_name='attached file'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='mime_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='MIME type'),
        ),
    ]
