# Generated by Django 4.0.2 on 2022-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_file_message_file_key_message_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_file_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='external file URL'),
        ),
    ]
