# Generated by Django 4.0.2 on 2022-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_external_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('S', 'System'), ('T', 'Text'), ('V', 'Voice'), ('a', 'Audio'), ('v', 'Video'), ('i', 'Image'), ('A', 'Attachment')], max_length=1),
        ),
    ]
