# Generated by Django 4.0.4 on 2022-05-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(blank=True, max_length=4000, verbose_name='option text')),
                ('position', models.PositiveSmallIntegerField(verbose_name='option position')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='chat.message', verbose_name='message')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
