# Generated by Django 4.1 on 2022-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_messageoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Not approved'), (1, 'Automatically approved'), (2, 'Approved by bot manager')], default=0),
        ),
    ]
