# Generated by Django 4.1 on 2022-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='command',
            field=models.CharField(blank=True, max_length=1000, verbose_name='command'),
        ),
    ]
